### ISSUE TITLE
关于EA实现的2个问题，线性层和normalization

### ISSUE THREAD

**Issue by YouJiacheng** [MenghaoGuo/EANet#11]
先reshape（view）再Conv1d和直接1*1 Conv2d有什么区别，为什么不直接用1*1 Conv2d呢？

而且这么看的话，EA和ResNet的bottleneck非常相似，都是沙漏状1*1 Conv2d中间夹一个模块，只不过ResNet夹的是BN-ReLU-3*3 Conv2d-BN-ReLU，而EA夹的是double normalization

另外，我把normalization从先在N=H*W维度上softmax再在k=S维度上L1 norm改成只在k=S维度上softmax，在简单的任务上性能没有显著差异，不知道作者有没有做相关的消融实验？（论文中没有提及）

**Comment by MenghaoGuo** [comment]
1. 没有区别，Conv1d / Conv2d / Linear 都可以用来实现。
2. 有区别，后续会放出一些 ablation，差异不太大，在我的某些实验里是有 0.1 - 0.3 的差异的。

**Comment by MenghaoGuo** [comment]
关于和 bottleneck 的相似的地方，我觉得这是一个非常有启发的地方，我们也正在做相关的实验。可以思考这么一件事情，如果 softmax 能实现全局交互的话，那么它就可以弥补 Conv 局部性的不足，可以弥补这种不足的话，是不是可以做一种这样的结构 ？ 用 Conv 做 local 语义信息的提取，用 softmax （normalization） 做 global 交互的网络结构，同时具备具有 CNN 和 Transformer 的优点。
