### ISSUE TITLE
关于 model_torch.py中的问题

### ISSUE THREAD

**Issue by 18456432930** [MenghaoGuo/EANet#17]
model_torch.py中有一段 from bn_lib.nn.modules import SynchronizedBatchNorm2d这样的程序，我使用时报错，我该怎么解决这个问题？

**Comment by MenghaoGuo** [comment]
这个文件我们使用的和 EMANet 同样的文件，您可以先用 https://github.com/XiaLiPKU/EMANet/tree/master/bn_lib 这个文件，后面我们也会上传一份。
