### ISSUE TITLE
Question about multi-head EA

### ISSUE THREAD

**Issue by easonyang1996** [MenghaoGuo/EANet#18]
Hi, Thanks for releasing the code!
Do you think the representation capability of MEA is lower than EA, since the external memories are shared across different heads?

**Comment by MenghaoGuo** [comment]
Hi, thanks for your attention. 
I don't think so. I think multi-head is important. It plays a role of implicitly ensembling and improves the results. Experiment results also reveal it.

**Comment by easonyang1996** [comment]
@MenghaoGuo 
So, the 'C' in Algorithm 2 (MEA) is not the 'C' in Algorithm 1(EA), right? 
If the C_{MEA} is a multiple of the C_{EA}, that makes sense.
