### ISSUE TITLE
The problem of  the program running on Cifar10/100

### ISSUE THREAD

**Issue by laohanlin** [MenghaoGuo/EANet#21]
Hi，Menghao. I run the command: **CUDA_VISIBLE_DEVICES=1,3 python transfer_learning.py** and want to verify the performance of EANet on Cifar10/100. But after two rounds of iteration, the loss function remains unchanged. And the value of ACC is always 10.000%. The result is shown in the figure below:
![屏幕截图 2021-06-09 105152](https://user-images.githubusercontent.com/71748257/125734797-8f1ec24e-85bd-4985-8238-aa37f0c6a3fb.png)
Could you please help me to solve this problem?

**Comment by MenghaoGuo** [comment]
I am willing to discuss and solve this problem with you, but I feel that this problem is not easy to describe clearly in a short time. You can send your WeChat to my e-mail: gmh20@mails.tsinghua.edu.cn. we can communicate more conveniently.
