### ISSUE TITLE
the code of multi head external attetion can't work

### ISSUE THREAD

**Issue by DRJYYDS** [MenghaoGuo/EANet#29]
![85ed43e6f2f7159a117ad374faa6570](https://user-images.githubusercontent.com/102657334/162726221-c19b1cc9-660f-46d1-a7e7-23c8c6c7dc1d.png)
It's obvious that the code is wrong. You should check the reshape and transpose part in your code.
And what is the coef? It has not been mentioned in the paper.
And also you didn't import the torch.
And the qkv_bias, qk_scale is not used here.
Did you really run the multi-head version in your paper?

**Comment by MenghaoGuo** [comment]
I think the code is correct.
We import toch in this [line](https://github.com/MenghaoGuo/EANet/blob/d7ae481b2b68858de6c9e4826eb27130f5d8bdf8/EAMLP/models/transformer_block.py#L9). 

You can read the code carefully and run it and you will find it is correct. 
 
Some code comments may inaccurate and we will organize this repo after this article is accepted.

**Comment by DRJYYDS** [comment]
> I think the code is correct. We import toch in this [line](https://github.com/MenghaoGuo/EANet/blob/d7ae481b2b68858de6c9e4826eb27130f5d8bdf8/EAMLP/models/transformer_block.py#L9).
> 
> You can read the code carefully and run it and you will find it is correct.
> 
> Some code comments may inaccurate and we will organize this repo after this article is accepted.

So the actual shape for X is [B,C,N]? or the code can't work at all.
![image](https://user-images.githubusercontent.com/102657334/163000320-f7f26288-e648-4e95-b3f2-290272b517cd.png)

Btw, the screenshot is from the file 'multi_head_attention_torch.py'. You did not import torch here.

**Comment by MenghaoGuo** [comment]
it is b n c and nn.Linear can be used in this situation.

We do not import this multi head file in the EAMLP，Please check it.
